### ISSUE TITLE
Game Icon Mismatch

### ISSUE THREAD

**Issue by FFFAS444** [A1mDev/hlstatsx-community-edition#1]
**Describe the bug**
So I installed hlstats with php8.1 I added CSS and tf2 servers but instead of showing their game icons, it's showing the hl2 icon instead.

**Screenshots**
https://imgur.com/a/HTfL9pX

**Environment**
- Webserver: apache2
- Hosting environment: VPS
- PHP version: 8.1
- Browser:  Chrome

**Comment by A1mDev** [comment]
I was unable to reproduce this issue.
