### ISSUE TITLE
Forum Signature

### ISSUE THREAD

**Issue by bobl61** [A1mDev/hlstatsx-community-edition#5]
Previously I was able to change `$font = IMAGE_PATH.'/sig/font/DejaVuSans.ttf';` to absolute path, then it worked. 
`$font = 'C:/xampp/htdocs/ggturbo.ddns.net/hlstatsimg/sig/font/DejaVuSans.ttf';`
That change is no longer working.

![2023-06-27_143451](https://github.com/A1mDev/hlstatsx-community-edition/assets/107001969/5609fb2b-59cb-4088-b512-84cd28203bfe)

Saw this in error logs:

`[Tue Jun 27 18:14:33.328722 2023] [php:notice] [pid 11664:tid 1792] [client 185.202.220.58:34584] PHP Deprecated:  Implicit conversion from float 0.1322222222222222 to int loses precision in C:\\xampp\\htdocs\\ggturbo.ddns.net\\sig.php on line 407, referer: https://ggturbo.ddns.net/hlstats.php?mode=playerinfo&player=1
[Tue Jun 27 18:14:33.329665 2023] [php:notice] [pid 11664:tid 1792] [client 185.202.220.58:34584] PHP Deprecated:  Implicit conversion from float 7.933333333333334 to int loses precision in C:\\xampp\\htdocs\\ggturbo.ddns.net\\sig.php on line 410, referer: https://ggturbo.ddns.net/hlstats.php?mode=playerinfo&player=1`

**Comment by A1mDev** [comment]
I can't reproduce this issue yet

**Comment by bobl61** [comment]
> I can't reproduce this issue yet

I reinstalled using your latest fork. All good now.
